class AddNewToSurvey < ActiveRecord::Migration[5.0]
  def change
    add_column :surveys, :a8,  :string
    add_column :surveys, :a9,  :string
    add_column :surveys, :a10, :integer
    add_column :surveys, :a11, :integer
    add_column :surveys, :a12, :string
    add_column :surveys, :a13, :integer
    add_column :surveys, :a14, :integer
    add_column :surveys, :a15, :string
    add_column :surveys, :a16, :integer
    add_column :surveys, :a17, :integer
    add_column :surveys, :a18, :string
    add_column :surveys, :a19, :integer
    add_column :surveys, :a20, :integer
    add_column :surveys, :a21, :string
    add_column :surveys, :a22, :integer
    add_column :surveys, :a23, :integer
    add_column :surveys, :a24, :string
    add_column :surveys, :a25, :integer
    add_column :surveys, :a26, :integer
    add_column :surveys, :a27, :string
    add_column :surveys, :a28, :integer
    add_column :surveys, :a29, :integer
    add_column :surveys, :a30, :string
    add_column :surveys, :a31, :integer
    add_column :surveys, :a32, :integer
    add_column :surveys, :a33, :string
    add_column :surveys, :a34, :integer
    add_column :surveys, :a35, :integer
    add_column :surveys, :a36, :string
    add_column :surveys, :a37, :integer
    add_column :surveys, :a38, :integer
    add_column :surveys, :a39, :string
    add_column :surveys, :a40, :integer
    add_column :surveys, :a41, :integer
    add_column :surveys, :a42, :string
    add_column :surveys, :a43, :integer
    add_column :surveys, :a44, :integer
    add_column :surveys, :a45, :string
    add_column :surveys, :a46, :integer
    add_column :surveys, :a47, :integer
    add_column :surveys, :a48, :string
    add_column :surveys, :a49, :string
    add_column :surveys, :a50, :string
    add_column :surveys, :a51, :string
    add_column :surveys, :a52, :string
    add_column :surveys, :a53, :string
  end
end
